// examples/vue-vite/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { useI18nKeyless, type Lang } from "i18n-keyless-vue";
import { SUPPORTED_LANGUAGES } from "./i18n";

// Three ways to translate, pick per site:
//  1. <T>texte</T>                       the component, for markup
//  2. t("texte", { context })            from useI18nKeyless(), for template expressions
//  3. getTranslation("texte")            the plain function, outside components
const { t, currentLanguage, setCurrentLanguage } = useI18nKeyless();

// A tiny two-view "router" (no router dependency) so the demo stays focused on
// i18n-keyless. Switching views is client-side navigation: translations persist across it.
const page = ref<"home" | "about">("home");

// Cycles through the supported languages. `setCurrentLanguage` updates the store and
// fetches the new language's translations; everything reading the store re-renders.
function switchLanguage() {
  const index = SUPPORTED_LANGUAGES.indexOf(currentLanguage.value as (typeof SUPPORTED_LANGUAGES)[number]);
  const next = SUPPORTED_LANGUAGES[(index + 1) % SUPPORTED_LANGUAGES.length];
  setCurrentLanguage(next as Lang);
}
</script>

<template>
  <main class="app">
    <header>
      <h1>i18n-keyless · Vite + Vue</h1>
      <nav>
        <button :class="{ active: page === 'home' }" @click="page = 'home'"><T>Accueil</T></button>
        <button :class="{ active: page === 'about' }" @click="page = 'about'"><T>À propos</T></button>
        <button class="switch" @click="switchLanguage">
          <T>Changer de langue</T> ({{ currentLanguage }})
        </button>
      </nav>
    </header>

    <!-- Page A: text written in the primary language (French), rendered through <T>.
         Note `replace` to inject a runtime value. -->
    <section v-if="page === 'home'" class="card">
      <p class="lang-line">
        <T :replace="{ '{lang}': currentLanguage ?? '' }">Langue : {lang}</T>
      </p>
      <p>
        <T>
          Voici une phrase disponible dans toutes vos langues, vous pouvez la modifier si vous le
          souhaitez.
        </T>
      </p>
      <p class="muted">
        <T>
          Attention aussi : les traductions n'ont lieu qu'une seule fois, comme une recherche Google :
          elles sont ensuite gardées en cache pour un chargement instantané.
        </T>
      </p>
      <input :placeholder="t('Votre email')" />
    </section>

    <!-- Page B: different strings than Home, through `t()` (for attributes and dynamic text)
         plus the `context` option: "8 heures" is "8 AM" (a time) or "8 hours" (a duration). -->
    <section v-else class="card">
      <h2><T>À propos de cette démo</T></h2>
      <p>{{ t("Ce texte est rendu avec la fonction t() au lieu du composant T.") }}</p>
      <p class="context-line">
        <code>8 heures</code> (heure) → <strong>{{ t("8 heures", { context: "heure" }) }}</strong>
        &nbsp;·&nbsp;
        <code>8 heures</code> (durée) → <strong>{{ t("8 heures", { context: "durée" }) }}</strong>
      </p>
    </section>
  </main>
</template>

// examples/react-native/App.tsx
import { useState } from "react";
import { SafeAreaView, View, Text, Pressable, StyleSheet } from "react-native";
import {
  I18nKeylessText,
  getTranslation,
  useCurrentLanguage,
  setCurrentLanguage,
  type Lang,
} from "i18n-keyless-react";
import { initI18n, SUPPORTED_LANGUAGES } from "./src/i18n";

// In React Native, <I18nKeylessText> must live inside a <Text> (it renders a string).
initI18n();

export default function App() {
  const [page, setPage] = useState<"home" | "about">("home");
  const current = (useCurrentLanguage() ?? "fr") as Lang;

  return (
    <SafeAreaView style={styles.screen}>
      <Text style={styles.h1}>i18n-keyless · React Native</Text>

      <View style={styles.nav}>
        <Pressable onPress={() => setPage("home")}>
          <Text style={[styles.tab, page === "home" && styles.active]}>
            <I18nKeylessText>Accueil</I18nKeylessText>
          </Text>
        </Pressable>
        <Pressable onPress={() => setPage("about")}>
          <Text style={[styles.tab, page === "about" && styles.active]}>
            <I18nKeylessText>À propos</I18nKeylessText>
          </Text>
        </Pressable>
        <Pressable
          onPress={() => {
            const list = SUPPORTED_LANGUAGES as readonly Lang[];
            setCurrentLanguage(list[(list.indexOf(current) + 1) % list.length]);
          }}
        >
          <Text style={[styles.tab, styles.switch]}>
            <I18nKeylessText>Changer de langue</I18nKeylessText> ({current})
          </Text>
        </Pressable>
      </View>

      {page === "home" ? <Home /> : <About />}
    </SafeAreaView>
  );
}

function Home() {
  const current = useCurrentLanguage();
  return (
    <View style={styles.card}>
      <Text style={styles.bold}>
        <I18nKeylessText replace={{ "{{current_lang}}": current ?? "" }}>
          {`Langue : {{current_lang}}`}
        </I18nKeylessText>
      </Text>
      <Text style={styles.body}>
        <I18nKeylessText>
          Voici une phrase disponible dans toutes vos langues, vous pouvez la modifier si vous le
          souhaitez.
        </I18nKeylessText>
      </Text>
    </View>
  );
}

function About() {
  useCurrentLanguage();
  // The imperative getTranslation() function + the `context` option.
  const intro = getTranslation(
    "Ce texte est rendu avec la fonction getTranslation() au lieu du composant <T>."
  );
  const asTime = getTranslation("8 heures", { context: "heure" });
  const asDuration = getTranslation("8 heures", { context: "durée" });
  return (
    <View style={styles.card}>
      <Text style={styles.bold}>
        <I18nKeylessText>À propos de cette démo</I18nKeylessText>
      </Text>
      <Text style={styles.body}>{intro}</Text>
      <Text style={styles.body}>
        8 heures → {asTime} (heure) · {asDuration} (durée)
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#0f1115", padding: 20 },
  h1: { color: "#e8eaed", fontSize: 20, fontWeight: "600", marginBottom: 16 },
  nav: { flexDirection: "row", gap: 8, marginBottom: 16, flexWrap: "wrap" },
  tab: { color: "#e8eaed", borderWidth: 1, borderColor: "#2a2f3a", borderRadius: 8, paddingVertical: 6, paddingHorizontal: 12 },
  active: { borderColor: "#6c8cff", backgroundColor: "#1b2030" },
  switch: { borderColor: "#3a4a6b", backgroundColor: "#1d2536" },
  card: { borderWidth: 1, borderColor: "#232834", borderRadius: 12, padding: 16, backgroundColor: "#14171e", gap: 8 },
  bold: { color: "#e8eaed", fontWeight: "600" },
  body: { color: "#cfd3da" },
});
